apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deleteuser-deployment
  labels:
    app: deleteuser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deleteuser
  template:
    metadata:
      labels:
        app: deleteuser
    spec:
      containers:
        - name: deleteuser
          image: deleteuser:2.0
          ports:
            - containerPort: 8777
      imagePullSecrets:
        - name: my-docker-secret