apiVersion: v1
kind: Service
metadata:
  name: editreservation-service
spec:
  selector:
    app: editreservation
  ports:
    - protocol: TCP
      port: 8777
      targetPort: 8777
  type: NodePort
