apiVersion: apps/v1
kind: Deployment
metadata:
  name:  getmenu-deployment
  labels:
    app: getmenu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getmenu
  template:
    metadata:
      labels:
        app: getmenu
    spec:
      containers:
        - name: getmenu
          image: getmenu:5.0
          ports:
            - containerPort: 8765
      imagePullSecrets:
        - name: my-docker-secret