apiVersion: apps/v1
kind: Deployment
metadata:
  name:  getreservations-deployment
  labels:
    app: getreservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getreservations
  template:
    metadata:
      labels:
        app: getreservations
    spec:
      containers:
        - name: getreservations
          image: getreservations:5.0
          ports:
            - containerPort: 8777
      imagePullSecrets:
        - name: my-docker-secret