apiVersion: v1
kind: Service
metadata:
  name: getreservations-service
spec:
  selector:
    app: getreservations
  ports:
    - protocol: TCP
      port: 8777
      targetPort: 8777
  type: NodePort
