apiVersion: apps/v1
kind: Deployment
metadata:
  name:  getreservationsrest-deployment
  labels:
    app: getreservationsrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getreservationsrest
  template:
    metadata:
      labels:
        app: getreservationsrest
    spec:
      containers:
        - name: getreservationsrest
          image: getreservationsrest:latest
          ports:
            - containerPort: 8777
      imagePullSecrets:
        - name: my-docker-secret