apiVersion: v1
kind: Service
metadata:
  name: getreservationsrest-service
spec:
  selector:
    app: getreservationsrest
  ports:
    - protocol: TCP
      port: 8777
      targetPort: 8777
  type: NodePort
