apiVersion: apps/v1
kind: Deployment
metadata:
  name:  getreservationsuser-deployment
  labels:
    app: getreservationsuser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getreservationsuser
  template:
    metadata:
      labels:
        app: getreservationsuser
    spec:
      containers:
        - name: getreservationsuser
          image: getreservationsuser:2.0
          ports:
            - containerPort: 8777
      imagePullSecrets:
        - name: my-docker-secret
