apiVersion: apps/v1
kind: Deployment
metadata:
  name:  login-deployment
  labels:
    app: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: login:5.0
          ports:
            - containerPort: 8777
      imagePullSecrets:
        - name: my-docker-secret
